name: pdf_translator
description: translate text in pdf files.
publish_to: 'none'
version: 0.1.5

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  audioplayers: ^3.0.1
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  simplytranslate: ^1.2.2
  syncfusion_flutter_pdfviewer: ^20.4.51
  translator: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.12.0"

flutter_icons:
  # android: "launcher_icon"
  # ios: true
  # image_path: "assets/i.png"
  # min_sdk_android: 21 # android min sdk min:16, default 21
  # web:
  #   generate: true
  #   image_path: "assets/i.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/i.png"
    icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "assets/i.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
