name: pdf_translator
description: translate text in pdf files.
publish_to: 'none'
version: 0.1.5

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  audioplayers: ^3.0.1
  cross_file: ^0.3.3+4
  desktop_drop: ^0.4.1
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: ^0.13.5
  simplytranslate: ^1.2.2
  syncfusion_flutter_pdfviewer: ^20.4.51
  translator: ^0.1.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.12.0"

flutter_icons:
  windows:
    generate: true
    image_path: "assets/i.png"
    icon_size: 48

flutter:
  uses-material-design: true
  assets:
    - assets/
